// Mocks generated by Mockito 5.4.6 from annotations
// in hnotes/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cosmos_sdk/cosmos_sdk.dart' as _i2;
import 'package:hnotes/infrastructure/blockchain/contract_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTendermintProvider_0 extends _i1.SmartFake
    implements _i2.TendermintProvider {
  _FakeTendermintProvider_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ContractRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContractRepository extends _i1.Mock
    implements _i3.ContractRepository {
  MockContractRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get rpcEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#rpcEndpoint),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#rpcEndpoint),
            ),
          )
          as String);

  @override
  String get restEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#restEndpoint),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#restEndpoint),
            ),
          )
          as String);

  @override
  String get contractAddress =>
      (super.noSuchMethod(
            Invocation.getter(#contractAddress),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#contractAddress),
            ),
          )
          as String);

  @override
  _i2.TendermintProvider get provider =>
      (super.noSuchMethod(
            Invocation.getter(#provider),
            returnValue: _FakeTendermintProvider_0(
              this,
              Invocation.getter(#provider),
            ),
          )
          as _i2.TendermintProvider);

  @override
  set provider(_i2.TendermintProvider? _provider) => super.noSuchMethod(
    Invocation.setter(#provider, _provider),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<Map<String, dynamic>?> queryContract(
    Map<String, dynamic>? queryMsg,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#queryContract, [queryMsg]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> getContractInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getContractInfo, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> queryContractRaw(List<int>? queryData) =>
      (super.noSuchMethod(
            Invocation.method(#queryContractRaw, [queryData]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> getContractCode() =>
      (super.noSuchMethod(
            Invocation.method(#getContractCode, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<bool> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>?> getChainInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getChainInfo, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> getConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> getState() =>
      (super.noSuchMethod(
            Invocation.method(#getState, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> getBalance(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getBalance, [address]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> getAllBalances() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBalances, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> getTokenInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getTokenInfo, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> getAllowance(
    String? owner,
    String? spender,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllowance, [owner, spender]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<Map<String, dynamic>?>> executeMultipleQueries(
    List<Map<String, dynamic>>? queries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#executeMultipleQueries, [queries]),
            returnValue: _i5.Future<List<Map<String, dynamic>?>>.value(
              <Map<String, dynamic>?>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>?>>);
}
