name: Build and Release Android

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build & Release Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Flutter Clean
        run: flutter clean

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version:' pubspec.yaml | sed 's/version:\s*\([0-9]*\.[0-9]*\.[0-9]*.*\)/\1/' | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Extracted version: $version"

      - name: Build APK
        run: flutter build apk --release --build-name=${{ steps.extract_version.outputs.version }} --build-number=${{ github.run_number }}

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/hnotes-v${{ steps.extract_version.outputs.version }}.apk

      - name: Create GitHub Tag and Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          name: v${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: build/app/outputs/flutter-apk/hnotes-v${{ steps.extract_version.outputs.version }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Deployment Summary
        run: |
          echo "## Release Summary:" >> $GITHUB_STEP_SUMMARY
          echo "### App version: ${{ steps.extract_version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "### 🕒 Released at: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "::notice::Build APK successfully!"
